#!/usr/bin/env bash

# fail fast
set -eu

# create netrc
cat >> $HOME/.netrc <<EOF
machine api.heroku.com
  login $HEROKU_API_USER
  password $HEROKU_API_KEY
EOF

echo "" >> Appfile

echo "Reading Appfile..."
while read app_release; do
  if [ -n "$app_release" ]; then
    echo "--> Processing $app_release"

    app_release_array=($app_release)
    app=${app_release_array[0]}
    release=${app_release_array[1]}

    slug_id=$(curl -s -n https://api.heroku.com/apps/$app/releases/$release \
      -H "Accept: application/vnd.heroku+json; version=3" | \
      python -c 'import json,sys;obj=json.load(sys.stdin);print obj["slug"]["id"]')

    slug_url=$(curl -s -n https://api.heroku.com/apps/$app/slugs/$slug_id \
      -H "Accept: application/vnd.heroku+json; version=3" | \
      python -c 'import json,sys;obj=json.load(sys.stdin);print obj["blob"]["url"]')

    echo "--> Downloading slug ${slug_id} for ${app}"
    curl -s -L "${slug_url}" | tar xzm --strip-components=2
  else
    echo "--> Done"
  fi
done </app/Appfile

rm $HOME/.netrc

if [ -f bin/web ]; then
  ./bin/web
else
  echo "No bin/web file found!"
fi
